ptrial <- function(amu,
                   bmu,
                   asigma,
                   bsigma,
                   an,
                   bn) {
  # get samples
  sample_a <- rnorm(n = an, mean = amu, sd = asigma)
  sample_b <- rnorm(n = bn, mean = bmu, sd = bsigma)

  # calculate t-test
  ttest <- t.test(sample_a, sample_b)

  # return pvalue
  return(p_value = ttest$p.value)
}

function(input, output, session) {
  pvals <- reactive({
    replicate(
      input$trials,
      ptrial(
        amu = input$amu,
        bmu = input$bmu,
        asigma = input$asigma,
        bsigma = input$bsigma,
        an = input$an,
        bn = input$bn
      )
    )
  })

  h2("Estimated distributions from reported group statsitics")
  output$densities <- renderPlot({
    ggplot() +
      stat_function(
        fun = dnorm,
        args = list(mean = input$amu, sd = input$asigma),
        alpha = 0.5,
        linetype = "dotted"
      ) +
      stat_function(
        fun = dnorm,
        args = list(mean = input$bmu, sd = input$bsigma),
        alpha = 0.5,
        linetype = "dashed"
      ) +
      geom_text(
        aes(x = x, y = y, label = label),
        data = tibble(
          x = c(input$amu, input$bmu),
          y = dnorm(
            c(input$amu, input$bmu),
            mean = c(input$amu, input$bmu),
            sd = c(input$asigma, input$bsigma)
          ) + 0.1,
          label = c("A", "B")
        ),
        alpha = 0.7,
        size = 8
      ) +
      geom_vline(xintercept =input$amu, lty=2 )+ # I think it is useful to see the "mean" on the plot but maybe better as a segment rather than a line so it stops at the height of the distribution and doesnt go all the way through
      geom_vline(xintercept =input$bmu, lty=2 )+
      theme_tufte(base_size = 20) +
      theme(
        axis.title.x = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank()
      ) +
      xlim(min(c(input$amu, input$bmu)) - 3 * max(c(input$asigma, input$bsigma)),
           max(c(input$amu, input$bmu)) + 3 * max(c(input$asigma, input$bsigma))) +
      labs(title = "Estimated distributions of groups A and B",
           caption = "Reported means for each group are indicated by vertical dashed lines")
  })

  h2("Simulation results")
  output$pvals <- renderPlot({
    reported_quant <- ecdf(pvals())(input$reportedp)

    shown_p <- input$reportedp + input$reportedp / 2

    shown_percent <- ecdf(pvals())(shown_p) %>% round(2) * 2


    tibble(p_value = pvals()) %>%
      ggplot(aes(x = p_value)) +
      geom_density() +
      theme_tufte(base_size = 20) +
      theme(
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank()
      ) +
      geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.3) +
      geom_vline(xintercept = input$reportedp,
                 linetype = "dotted", size = 2, alpha = 0.6) +
      annotate(
        "rect",
        xmin = input$reportedp,
        xmax = max(pvals()),
        ymin = 0,
        ymax = Inf,
        alpha = 0.1
      ) +
      labs(
        title = str_wrap(
          glue(
            "Distribution of of p-values generated by {input$trials} t-tests of random samples drawn from distributions of groups"
          )
        ),
        subtitle = str_wrap(
          glue(
            "{(1 - round(reported_quant, 2)) * 100} per cent of p-values are greater (shaded region) than reported p-value {input$reportedp}"
          )
        ),
        x = "p value",
        caption = "Reported p-value indicated by vertical dotted line"
      )

  })

}
