p_sim_plot <- function(pvals, reported_p, trials){
  if (is.null(pvals)) return(ggplot())

  reported_quant <- ecdf(pvals)(reported_p)

  shown_p <- reported_p + reported_p / 2

  shown_percent <- ecdf(pvals)(shown_p) %>% round(2) * 2

  tibble(p_value = pvals) %>%
    ggplot(aes(x = p_value)) +
    geom_density() +
    theme_tufte(base_size = 20) +
    theme(
      axis.line.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.text.y = element_blank(),
      axis.title.y = element_blank()
    ) +
    geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.3) +
    geom_vline(xintercept = reported_p,
               linetype = "dotted", size = 2, alpha = 0.6) +
    annotate(
      "rect",
      xmin = reported_p,
      xmax = max(pvals),
      ymin = 0,
      ymax = Inf,
      alpha = 0.1
    ) +
    labs(
      title = str_wrap(
        glue(
          "Distribution of of p-values generated by {trials} ANOVA of random samples drawn from distributions of groups"
        )
      ),
      subtitle = str_wrap(
        glue(
          "{(1 - round(reported_quant, 2)) * 100} per cent of p-values are greater (shaded region) than reported p-value {reported_p}"
        )
      ),
      x = "p-value",
      caption = "Reported p-value indicated by vertical dotted line"
    ) +
    xlim(0,1)

}
